implements MVC pattern, adds topics endpoint
jbhall4291/backend-nc-news pull request #2
Opened 2023-02-20 15:54 UTC by jbhall4291

this is for task 3. GET /api/topics

2023-02-20 16:09 UTC, Beth-McCormack commented on __tests__/app.test.js
> +  });
This test is redundant as the next tests will not pass unless status code is 200.

2023-02-20 16:20 UTC, Beth-McCormack commented on app.js
> +app.use(express.json());
Please remove this until its needed

2023-02-20 16:24 UTC, Beth-McCormack requested changes
see comments

2023-02-21 10:27 UTC, johnhutcheon approved these changes
Thanks for making the changes Johnny, all good to merge!

2023-02-21 10:56 UTC, merged